### ISSUE TITLE
(Feature - Qa) Postman 

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/Sprint-5-Frontend#10]
## Descripción
Se pide utilizar POSTMAN en las APis utilizadas y base de datos

## Tareas
* [x] Testeo: Utilice Postman en una APi
* [x] Documentacion: Genere un documento mediante la información obtenida y verificar si obtuvo errores

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 23-06-2024

**Comment by VlackVist** [comment]
https://documenter.getpostman.com/view/36149533/2sA3XWdymh

Documentación de la colección de la request de cada microservicio

**Comment by VlackVist** [comment]
https://www.postman.com/vlackvist/workspace/utemtx-tests/flow/6678a5834bf493003289cd45

Aqui estan hechos los flows para cada request para, generar registro de error y mostrar en caso de exito.
